### PR TITLE
Added some setup instructions

### PR DESCRIPTION
**Pull request by mliu7**
This repo is great for us Python users! I just added some basic setup instructions to hopefully reduce the barrier for people to adopt this.

Thanks so much for making it!

### CODE REVIEW

**Comment by ThiefMaster** [comment]
I'd mention that it's a good idea to install it into a virtualenv.

**Comment by mliu7** [comment]
Sure thing. I'll add instructions for that and resubmit.

**Comment by ThiefMaster** [comment]
Hey, no need to close it - simply amend your commit and force-push.

**Comment by mliu7** [comment]
Ah, gotcha. I updated the readme and pushed!

**Comment by pakal** [comment]
Doesn't just a "pip install" do the same job as these steps ?

**Comment by ThiefMaster** [comment]
Yes. `pip install` is the way to go. Or maybe even `pipx` nowadays...

**Pull request closed without merging**
